# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

date_original <- function(file) {
    .Call('rosettR_date_original', PACKAGE = 'rosettR', file)
}

count_outside <- function(s_im, s_rad, s_dx, s_dy, s_thresh) {
    .Call('rosettR_count_outside', PACKAGE = 'rosettR', s_im, s_rad, s_dx, s_dy, s_thresh)
}

round_binary <- function(s_im) {
    .Call('rosettR_round_binary', PACKAGE = 'rosettR', s_im)
}

closest_point <- function(s_im, s_points, s_nfeatures) {
    .Call('rosettR_closest_point', PACKAGE = 'rosettR', s_im, s_points, s_nfeatures)
}

normalpostp <- function(x, mu, sigma, lambda) {
    .Call('rosettR_normalpostp', PACKAGE = 'rosettR', x, mu, sigma, lambda)
}

