// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// date_original
CharacterVector date_original(SEXP file);
RcppExport SEXP rosettR_date_original(SEXP fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type file(fileSEXP);
    __result = Rcpp::wrap(date_original(file));
    return __result;
END_RCPP
}
// count_outside
NumericVector count_outside(SEXP s_im, SEXP s_rad, SEXP s_dx, SEXP s_dy, SEXP s_thresh);
RcppExport SEXP rosettR_count_outside(SEXP s_imSEXP, SEXP s_radSEXP, SEXP s_dxSEXP, SEXP s_dySEXP, SEXP s_threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type s_im(s_imSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_rad(s_radSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_dx(s_dxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_dy(s_dySEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_thresh(s_threshSEXP);
    __result = Rcpp::wrap(count_outside(s_im, s_rad, s_dx, s_dy, s_thresh));
    return __result;
END_RCPP
}
// round_binary
NumericMatrix round_binary(SEXP s_im);
RcppExport SEXP rosettR_round_binary(SEXP s_imSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type s_im(s_imSEXP);
    __result = Rcpp::wrap(round_binary(s_im));
    return __result;
END_RCPP
}
// closest_point
NumericMatrix closest_point(SEXP s_im, SEXP s_points, SEXP s_nfeatures);
RcppExport SEXP rosettR_closest_point(SEXP s_imSEXP, SEXP s_pointsSEXP, SEXP s_nfeaturesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type s_im(s_imSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_points(s_pointsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_nfeatures(s_nfeaturesSEXP);
    __result = Rcpp::wrap(closest_point(s_im, s_points, s_nfeatures));
    return __result;
END_RCPP
}
// normalpostp
List normalpostp(SEXP x, SEXP mu, SEXP sigma, SEXP lambda);
RcppExport SEXP rosettR_normalpostp(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mu(muSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambda(lambdaSEXP);
    __result = Rcpp::wrap(normalpostp(x, mu, sigma, lambda));
    return __result;
END_RCPP
}
